# Generated by Django 4.0.4 on 2022-05-26 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('given_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='추천메타아이디')),
                ('gender', models.CharField(max_length=10, null=True, verbose_name='성별')),
                ('birth_year', models.DateTimeField(null=True, verbose_name='생일년도')),
                ('birth_mmdd', models.DateTimeField(null=True, verbose_name='생일월일')),
                ('sido_sigungu_1', models.CharField(max_length=100, null=True, verbose_name='선호지역 시도 시군구1')),
                ('satisfaction1', models.IntegerField(null=True, verbose_name='선호지역1의 만족도')),
                ('sido_sigungu_2', models.CharField(max_length=100, null=True, verbose_name='선호지역 시도 시군구2')),
                ('satisfaction2', models.IntegerField(null=True, verbose_name='선호지역2의 만족도')),
                ('sido_sigungu_3', models.CharField(max_length=100, null=True, verbose_name='선호지역 시도 시군구3')),
                ('satisfaction3', models.IntegerField(null=True, verbose_name='선호지역3의 만족도')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='작성날짜')),
                ('earnings', models.IntegerField(null=True, verbose_name='수입')),
                ('spec', models.CharField(max_length=100, null=True, verbose_name='학력')),
                ('com_code_rg_id', models.ForeignKey(db_column='com_code_rg_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='공통코드_거주지역아이디', to='given_home.com_code', verbose_name='공통코드_거주지역아이디')),
                ('com_code_tm_id', models.ForeignKey(db_column='com_code_tm_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='공통코드_선호테마아이디', to='given_home.com_code', verbose_name='공통코드_선호테마아이디')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.users', verbose_name='작성자')),
            ],
            options={
                'verbose_name': 'survey',
                'verbose_name_plural': 'survey',
                'db_table': 'survey',
            },
        ),
        migrations.CreateModel(
            name='Chucheon_Spot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='아이디')),
                ('rate', models.FloatField(null=True, verbose_name='일치율')),
                ('rc_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='추천일자')),
                ('star', models.FloatField(null=True, verbose_name='만족도')),
                ('rc_id', models.ForeignKey(db_column='rc_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chucheon.survey', verbose_name='추천테마 아이디')),
                ('trip_id', models.ForeignKey(db_column='trip_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='given_home.tour_spots', verbose_name='여행지 아이디')),
                ('user_id', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.users', verbose_name='회원 아이디')),
            ],
            options={
                'verbose_name': 'chucheon_spot',
                'verbose_name_plural': 'chucheon_spot',
                'db_table': 'chucheon_spot',
            },
        ),
        migrations.CreateModel(
            name='Ai_Result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='아이디')),
                ('rc_loc_1_1', models.CharField(max_length=100, null=True, verbose_name='추천지역1_1')),
                ('rc_loc_1_2', models.CharField(max_length=100, null=True, verbose_name='추천지역1_2')),
                ('rc_loc_1_3', models.CharField(max_length=100, null=True, verbose_name='추천지역1_3')),
                ('rc_loc_2_1', models.CharField(max_length=100, null=True, verbose_name='추천지역2_1')),
                ('rc_loc_2_2', models.CharField(max_length=100, null=True, verbose_name='추천지역2_2')),
                ('rc_loc_2_3', models.CharField(max_length=100, null=True, verbose_name='추천지역2_3')),
                ('rc_loc_3_1', models.CharField(max_length=100, null=True, verbose_name='추천지역3_1')),
                ('rc_loc_3_2', models.CharField(max_length=100, null=True, verbose_name='추천지역3_2')),
                ('rc_loc_3_3', models.CharField(max_length=100, null=True, verbose_name='추천지역3_2')),
                ('rc_id', models.ForeignKey(db_column='rc_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chucheon.survey', verbose_name='추천테마 아이디')),
                ('userid', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.users', verbose_name='회원 아이디')),
            ],
            options={
                'verbose_name': 'ai_result',
                'verbose_name_plural': 'ai_result',
                'db_table': 'ai_result',
            },
        ),
    ]
