# Generated by Django 4.0.4 on 2022-05-26 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Com_Code',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='아이디')),
                ('com_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='공통코드')),
                ('code_nm', models.CharField(blank=True, max_length=100, null=True, verbose_name='코드명')),
                ('upper_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='상위코드')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='설명')),
            ],
            options={
                'db_table': 'com_code',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Group_Code',
            fields=[
                ('gr_code', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='공통그룹코드')),
                ('gr_code_nm', models.CharField(blank=True, max_length=100, null=True, verbose_name='공통그룹코드명')),
                ('upper_gr_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='상위그룹코드')),
                ('gr_comment', models.TextField(blank=True, null=True, verbose_name='설명')),
            ],
            options={
                'db_table': 'group_code',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tour_Spots',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='아이디')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='여행지명')),
                ('add_detail', models.CharField(blank=True, max_length=100, null=True, verbose_name='여행지세부주소')),
                ('gps_x', models.FloatField(blank=True, null=True, verbose_name='x좌표')),
                ('gps_y', models.FloatField(blank=True, null=True, verbose_name='y좌표')),
                ('image_src', models.CharField(blank=True, max_length=100, null=True, verbose_name='이미지_경로')),
                ('tel', models.CharField(blank=True, max_length=100, null=True, verbose_name='전화번호')),
                ('hits', models.IntegerField(blank=True, null=True, verbose_name='조회수')),
                ('com_code_rg_id', models.ForeignKey(db_column='com_code_rg_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='공통코드_지역아이디', to='given_home.com_code', verbose_name='공통코드_지역아이디')),
                ('com_code_tm_id', models.ForeignKey(db_column='com_code_tm_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='공통코드_테마아이디', to='given_home.com_code', verbose_name='공통코드_테마아이디')),
            ],
            options={
                'verbose_name': '여행지',
                'verbose_name_plural': '여행지',
                'db_table': 'tour_spots',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='com_code',
            name='gr_code',
            field=models.ForeignKey(db_column='gr_code', on_delete=django.db.models.deletion.CASCADE, to='given_home.group_code', verbose_name='공통그룹코드'),
        ),
    ]
