# Generated by Django 4.0.4 on 2022-05-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='사용자ID')),
                ('password', models.CharField(max_length=15, verbose_name='사용자PW')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='가입날짜')),
                ('modifier_id', models.CharField(max_length=30, null=True, verbose_name='수정자ID')),
                ('updated_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='수정날짜')),
                ('del_yn', models.CharField(default='N', max_length=30, verbose_name='탈퇴유무')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'users',
            },
        ),
    ]
